spring:
  datasource:
    url: jdbc:mysql://172.18.10.210:3306/hn_chat?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: zlhn-test
    password: zlhn201912
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      maxActive: 100
      minIdle: 5
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 30
      filters: stat

redisson:
  password:
  scanInterval: 5000 #milliseconds
  nodes:
    - redis://172.18.10.211:8001
    - redis://172.18.10.211:8002
    - redis://172.18.10.211:8003
    - redis://172.18.10.211:8004
    - redis://172.18.10.211:8005
    - redis://172.18.10.211:8006

system:
  file-domain: http://172.18.10.211:9000
  save-file-path: F:/chat
  minio:
    end-point: http://172.18.10.211:9000
    access-key: minioadmin
    secret-key: minioadmin
    minio-bucket: chat