spring:
  datasource:
    url: jdbc:mysql://192.168.1.8:3306/chat?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      maxActive: 100
      minIdle: 5
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 30
      filters: stat

redisson:
  password:
  mode: singleton  #cluster-集群模式 singleton-单机模式
  scanInterval: 5000 #milliseconds
  nodes:
    - redis://192.168.1.7:6379
    - redis://172.18.10.211:8001
    - redis://172.18.10.211:8002
    - redis://172.18.10.211:8003
    - redis://172.18.10.211:8004
    - redis://172.18.10.211:8005
    - redis://172.18.10.211:8006

system:
  default-avatar: http://192.168.1.7:9000/chat/default_avatar.png
  default-group-avatar: http://192.168.1.7:9000/chat/group.png
  file-domain: http://192.168.1.7:9000
  save-file-path: /chat
  illegal-file: .exe.bat.sh.js
  minio:
    end-point: http://192.168.1.7:9000
    access-key: admin
    secret-key: gb840925
    minio-bucket: chat

  sms:
    merchant: huanuo
    key: 4
    secret: C4A9914E99C1F38C17259149A7AE9EC3
    account: huanuo
    gateway-url: https://api.hvo.net.cn/smsJson.aspx
    rate-limit: 10
    template: 【中联华诺】您的短信验证码：%s，有效期为5分钟，请勿泄露给他人。如非本人操作，请忽略此短信。